# Generated by Django 6.0.3 on 2026-04-06 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("new_lead_created", "New Lead Created"),
                            ("lead_status_changed", "Lead Status Changed"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="inactive",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "workflows",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                (
                    "operator",
                    models.CharField(
                        choices=[("equals", "Equals"), ("not_equals", "Not Equals")],
                        default="equals",
                        max_length=30,
                    ),
                ),
                ("field_value", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_conditions",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("assign_agent", "Assign Agent"),
                            ("create_task", "Create Task"),
                            ("send_notification", "Send Notification"),
                            ("send_email", "Send Email"),
                        ],
                        max_length=50,
                    ),
                ),
                ("action_order", models.PositiveIntegerField()),
                ("config", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_actions",
                "ordering": ["action_order", "id"],
                "unique_together": {("workflow", "action_order")},
            },
        ),
    ]
